apiVersion: v1
kind: Service
metadata:
  name: service-clmfe-__deployEnv__
  namespace: ns-__deployEnv__
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: clmfe-__deployEnv__
    apptype: pulse-__deployEnv__
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: clmfe-__deployEnv__
    apptype: pulse-__deployEnv__
  type: LoadBalancer